# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 04:35
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pixelfields_smart_selects.db_fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('periodo', models.CharField(max_length=1)),
                ('inicial', models.DateField(blank=True, null=True)),
                ('actualizado', models.DateField(blank=True, null=True)),
                ('final', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'A\xf1o',
            },
        ),
        migrations.CreateModel(
            name='CatInversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=80)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('destacar', models.BooleanField(default=False)),
                ('color', models.CharField(default=b'#2b7ab3', max_length=8)),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Categor\xeda de inversi\xf3n',
                'verbose_name_plural': 'Categor\xedas de inversi\xf3n',
            },
        ),
        migrations.CreateModel(
            name='FuenteFmto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Fuente de financiamiento',
                'verbose_name_plural': 'Fuentes de financiamiento',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('periodo', models.CharField(max_length=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
                ('municipio', pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'ordering': ['anio', 'periodo', 'municipio'],
            },
        ),
        migrations.CreateModel(
            name='GastoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('cuenta', models.CharField(max_length=400)),
                ('asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ejecutado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Gasto')),
            ],
            options={
                'ordering': ['gasto', 'codigo'],
                'verbose_name': 'Detalle de gastos',
                'verbose_name_plural': 'Detalles de gastos',
            },
        ),
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('imagen_objetivo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'grafico')),
                ('imagen_actual', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'grafico')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Gr\xe1fico',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('periodo', models.CharField(max_length=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
                ('municipio', pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'ordering': ['anio', 'periodo', 'municipio'],
            },
        ),
        migrations.CreateModel(
            name='IngresoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('cuenta', models.CharField(max_length=400)),
                ('asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ejecutado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ingreso')),
            ],
            options={
                'ordering': ['ingreso', 'codigo'],
                'verbose_name': 'Detalle de ingresos',
                'verbose_name_plural': 'Detalles de ingresos',
            },
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremunic', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('periodo', models.CharField(max_length=1)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'ordering': ['anio', 'periodo', 'municipio'],
                'verbose_name': 'Inversi\xf3n',
                'verbose_name_plural': 'Inversiones',
            },
        ),
        migrations.CreateModel(
            name='InversionFuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField(verbose_name='A\xf1o')),
                ('periodo', models.CharField(max_length=1)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
                ('municipio', pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'ordering': ['anio', 'periodo', 'municipio'],
                'verbose_name': 'Inversi\xf3n de fuentes de financiamiento',
                'verbose_name_plural': 'Inversiones de fuentes de financiamiento',
            },
        ),
        migrations.CreateModel(
            name='InversionFuenteDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ejecutado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente', pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FuenteFmto')),
                ('inversionfuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InversionFuente')),
            ],
            options={
                'ordering': ['inversionfuente', 'tipofuente', 'fuente'],
                'verbose_name': 'Detalle de inversi\xf3n por fuente',
                'verbose_name_plural': 'Detalles de inversi\xf3n por fuente',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'organizacion')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Organizaci\xf3n',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='OrigenGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Origen de los gastos',
                'verbose_name_plural': 'Origenes de los gastos',
            },
        ),
        migrations.CreateModel(
            name='OrigenRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Origen de los recursos',
                'verbose_name_plural': 'Origenes de los recursos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=500)),
                ('areageografica', models.CharField(blank=True, choices=[(b'U', b'Urbana'), (b'R', b'Rural'), (b'O', b'Otros')], max_length=1, null=True)),
                ('asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ejecutado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ficha', models.FileField(blank=True, null=True, upload_to=b'proyecto')),
                ('catinversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_inversion', to='core.CatInversion', verbose_name='Categor\xeda de Inversi\xf3n')),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversion', to='core.Inversion')),
            ],
            options={
                'ordering': ['inversion', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubSubTipoGasto',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='core.OrigenGasto')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Sub sub tipo de gastos',
                'verbose_name_plural': 'Sub sub tipos de gastos',
            },
        ),
        migrations.CreateModel(
            name='SubSubTipoIngreso',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
                ('origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='core.OrigenRecurso')),
            ],
            options={
                'ordering': ['codigo'],
                'verbose_name': 'Sub-subtipo de ingreso',
                'verbose_name_plural': 'Sub-subtipos de ingreso',
            },
        ),
        migrations.CreateModel(
            name='SubTipoGasto',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Sub tipo de gastos',
                'verbose_name_plural': 'Sub tipos de gastos',
            },
        ),
        migrations.CreateModel(
            name='SubTipoIngreso',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'verbose_name': 'Subtipo de ingreso',
                'verbose_name_plural': 'Subtipos de ingreso',
            },
        ),
        migrations.CreateModel(
            name='TipoFuenteFmto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Tipo de Fuente de financiamiento',
                'verbose_name_plural': 'Tipos de Fuentes de financiamiento',
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
                ('clasificacion', models.IntegerField(choices=[(b'0', b'Gasto Corriente'), (b'1', b'Gasto de Capital')], default=0, null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'verbose_name': 'Tipo de gastos',
                'verbose_name_plural': 'Tipos de gastos',
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
                ('clasificacion', models.IntegerField(choices=[(0, b'Ingreso Corriente'), (1, b'Ingreso Capital')], default=0, null=True)),
            ],
            options={
                'ordering': ['codigo'],
                'verbose_name': 'Tipo de ingreso',
                'verbose_name_plural': 'Tipos de ingreso',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Tipo de proyectos',
                'verbose_name_plural': 'Tipos de proyectos',
            },
        ),
        migrations.AddField(
            model_name='subtipoingreso',
            name='tipoingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='core.TipoIngreso'),
        ),
        migrations.AddField(
            model_name='subtipogasto',
            name='tipogasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='core.TipoGasto'),
        ),
        migrations.AddField(
            model_name='subsubtipoingreso',
            name='subtipoingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipo', to='core.SubTipoIngreso'),
        ),
        migrations.AddField(
            model_name='subsubtipogasto',
            name='subtipogasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipo', to='core.SubTipoGasto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipoproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_proyecto', to='core.TipoProyecto'),
        ),
        migrations.AddField(
            model_name='inversionfuentedetalle',
            name='tipofuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoFuenteFmto'),
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='subsubtipoingreso',
            field=pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubSubTipoIngreso'),
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='subtipoingreso',
            field=pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubTipoIngreso'),
        ),
        migrations.AddField(
            model_name='ingresodetalle',
            name='tipoingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoIngreso'),
        ),
        migrations.AddField(
            model_name='gastodetalle',
            name='subsubtipogasto',
            field=pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubSubTipoGasto'),
        ),
        migrations.AddField(
            model_name='gastodetalle',
            name='subtipogasto',
            field=pixelfields_smart_selects.db_fields.ChainedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubTipoGasto'),
        ),
        migrations.AddField(
            model_name='gastodetalle',
            name='tipogasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoGasto'),
        ),
        migrations.AddField(
            model_name='fuentefmto',
            name='tipofuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoFuenteFmto'),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together=set([('inversion', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='inversion',
            unique_together=set([('anio', 'periodo', 'municipio')]),
        ),
        migrations.AlterUniqueTogether(
            name='ingresodetalle',
            unique_together=set([('ingreso', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='ingreso',
            unique_together=set([('anio', 'periodo', 'municipio')]),
        ),
        migrations.AlterUniqueTogether(
            name='gastodetalle',
            unique_together=set([('gasto', 'codigo')]),
        ),
        migrations.AlterUniqueTogether(
            name='gasto',
            unique_together=set([('anio', 'periodo', 'municipio')]),
        ),
    ]
