# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-21 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoRenglon',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('subsubtipogasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubSubTipoGasto')),
            ],
            options={
                'ordering': ['subsubtipogasto', 'codigo'],
                'verbose_name': 'Rengl\xf3n Gasto',
            },
        ),
        migrations.CreateModel(
            name='IngresoRenglon',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('subsubtipoingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubSubTipoIngreso')),
            ],
            options={
                'ordering': ['subsubtipoingreso', 'codigo'],
                'verbose_name': 'Rengl\xf3n Ingreso',
            },
        ),
    ]
