# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_renglongasto_rengloningreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastodetalle',
            name='codigo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.GastoRenglon'),
        ),
        migrations.AlterField(
            model_name='ingresodetalle',
            name='codigo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.IngresoRenglon'),
        ),
    ]
