# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-21 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_renglongasto_rengloningreso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RenglonIngreso',
            new_name='IngresoRenglon',
        ),
    ]
