# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-21 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191120_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RenglonGasto',
            new_name='GastoRenglon',
        ),
    ]
