# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 02:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191023_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuentefmto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='origengasto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='origenrecurso',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='subsubtipogasto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='subsubtipoingreso',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='subtipogasto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='subtipoingreso',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='tipofuentefmto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='tipogasto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='tipoingreso',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        # migrations.AlterUniqueTogether(
        #    name='ingresodetalle',
        #    unique_together=set([('ingreso', 'codigo')]),
        # ),
    ]
