# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191111_2034'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingresodetalle',
            unique_together=set([('ingreso', 'codigo')]),
        ),
    ]
