# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191216_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresodetalle',
            name='sub3tipoingreso',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sub3TipoIngreso'),
        ),
    ]
