# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191111_2036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gastodetalle',
            unique_together=set([('gasto', 'codigo')]),
        ),
    ]
