# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [ 
        ('core', '0008_sub3tipoingreso_origen'),
    ]   

    operations = [ 
        migrations.AlterField(
            model_name='sub3tipoingreso',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen_recurso', to='core.OrigenRecurso'),
        ),
    ]  
