# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191111_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='inversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversion', to='core.Inversion'),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together=set([('inversion', 'codigo')]),
        ),
    ]
