# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-13 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lugar', '0020_auto_20191111_2034'),
        ('core', '0009_auto_20191111_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
