# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-21 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200114_1422'),
        ('core', '0009_auto_20200121_1058'),
    ]

    operations = [
    ]
