# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191113_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anio',
            options={'verbose_name': 'A\xf1o'},
        ),
        migrations.AlterModelOptions(
            name='fuentefmto',
            options={'ordering': ['nombre'], 'verbose_name': 'Fuente de financiamiento', 'verbose_name_plural': 'Fuentes de financiamiento'},
        ),
        migrations.AlterModelOptions(
            name='grafico',
            options={'ordering': ['nombre'], 'verbose_name': 'Gr\xe1fico'},
        ),
        migrations.AlterModelOptions(
            name='inversionfuente',
            options={'verbose_name': 'Inversion de fuentes de financiamiento', 'verbose_name_plural': 'Inversiones de fuentes de financiamiento'},
        ),
        migrations.AlterModelOptions(
            name='inversionfuentedetalle',
            options={'ordering': ['inversionfuente'], 'verbose_name': 'Detalle de inversion por fuente', 'verbose_name_plural': 'Detalles de inversion por fuente'},
        ),
        migrations.AlterModelOptions(
            name='organizacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Organizaci\xf3n', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipofuentefmto',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Fuente de financiamiento', 'verbose_name_plural': 'Tipos de Fuentes de financiamiento'},
        ),
        migrations.AlterField(
            model_name='catinversion',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fuentefmto',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='grafico',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='origenrecurso',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='origenrecurso',
            name='shortname',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tipofuentefmto',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
