# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200121_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento'),
        ),
    ]
