# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-23 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200121_1431'),
        ('core', '0010_merge_20200121_1106'),
    ]

    operations = [
    ]
