# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20200122_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='origenrecurso',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
