# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191114_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inversion',
            options={'ordering': ['fecha'], 'verbose_name': 'Inversi\xf3n', 'verbose_name_plural': 'Inversiones'},
        ),
        migrations.AlterField(
            model_name='anio',
            name='anio',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='origengasto',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
