# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-14 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0021_auto_20191113_1220'),
        ('core', '0014_auto_20191114_0943'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gasto',
            unique_together=set([('anio', 'periodo', 'municipio')]),
        ),
        migrations.AlterUniqueTogether(
            name='ingreso',
            unique_together=set([('anio', 'periodo', 'municipio')]),
        ),
        migrations.AlterUniqueTogether(
            name='inversion',
            unique_together=set([('anio', 'periodo', 'municipio')]),
        ),
    ]
