# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_origenrecurso_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origenrecurso',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Origen de los recursos',
                     'verbose_name_plural': 'Origenes de los recursos'},
        ),
        migrations.AddField(
            model_name='origengasto',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
