# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191114_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['anio', 'periodo', 'municipio']},
        ),
        migrations.AlterModelOptions(
            name='gastodetalle',
            options={'ordering': ['gasto', 'codigo'], 'verbose_name': 'Detalle de gastos', 'verbose_name_plural': 'Detalles de gastos'},
        ),
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['anio', 'periodo', 'municipio']},
        ),
        migrations.AlterModelOptions(
            name='ingresodetalle',
            options={'ordering': ['ingreso', 'codigo'], 'verbose_name': 'Detalle de ingresos', 'verbose_name_plural': 'Detalles de ingresos'},
        ),
        migrations.AlterModelOptions(
            name='inversion',
            options={'ordering': ['anio', 'periodo', 'municipio'], 'verbose_name': 'Inversi\xf3n', 'verbose_name_plural': 'Inversiones'},
        ),
        migrations.AlterModelOptions(
            name='inversionfuente',
            options={'ordering': ['anio', 'periodo', 'municipio'], 'verbose_name': 'Inversi\xf3n de fuentes de financiamiento', 'verbose_name_plural': 'Inversiones de fuentes de financiamiento'},
        ),
        migrations.AlterModelOptions(
            name='inversionfuentedetalle',
            options={'ordering': ['inversionfuente', 'tipofuente', 'fuente'], 'verbose_name': 'Detalle de inversi\xf3n por fuente', 'verbose_name_plural': 'Detalles de inversi\xf3n por fuente'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['inversion', 'codigo']},
        ),
    ]
