# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200128_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origengasto',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Origen de los gastos', 'verbose_name_plural': 'Origenes de los gastos'},
        ),
        migrations.AddField(
            model_name='subsubtipogasto',
            name='clasificacion',
            field=models.IntegerField(choices=[(b'0', b'Gasto Corriente'), (b'1', b'Gasto de Capital')], default=0, null=True),
        ),
    ]
