# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200206_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubtipogasto',
            name='clasificacion',
            field=models.IntegerField(choices=[(b'0', b'Gasto Corriente'), (b'1', b'Gasto de Capital'), (b'2', b'Otra')], default=0, null=True),
        ),
    ]
