# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200206_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoingreso',
            name='ingreso_propio',
            field=models.BooleanField(default=True),
        ),
    ]
