# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-17 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tipoingreso_nuevo_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio_Transferencias',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('periodo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'A\xf1os Transferencias',
            },
        ),
    ]
