# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-17 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_anio_transferencias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anio_Transferencias',
            new_name='AnioTransferencias',
        ),
    ]
