# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-17 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200217_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnioTransferencias',
            new_name='AnioTransferencia',
        ),
    ]
