# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-17 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200217_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='inversion_publica',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='partida_presupuestaria',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='pgr',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='pip',
        ),
        migrations.AddField(
            model_name='aniotransferencia',
            name='inversion_publica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='aniotransferencia',
            name='partida_presupuestaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='aniotransferencia',
            name='pgr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='aniotransferencia',
            name='pip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
