# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200217_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniotransferencia',
            name='recurso_tesoro_pip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
