# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_aniotransferencia_recurso_tesoro_pip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aniotransferencia',
            name='partida_presupuestaria',
        ),
    ]
