# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_aniotransferencia_partida_presupuestaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniotransferencia',
            name='pgr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
