# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200218_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniotransferencia',
            name='pgr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
