# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200218_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniotransferencia',
            name='pip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='aniotransferencia',
            name='recurso_tesoro_pip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
