# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-04 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200302_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inversion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
