# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-06 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200304_0004'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gastodetalle',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ingresodetalle',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='proyecto',
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='ingresodetalle',
            name='subsubtipoingreso',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubSubTipoIngreso'),
        ),
        migrations.AlterField(
            model_name='ingresodetalle',
            name='subtipoingreso',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubTipoIngreso'),
        ),
        migrations.AlterField(
            model_name='tipogasto',
            name='clasificacion',
            field=models.IntegerField(choices=[(
                0, b'Gasto Corriente'), (1, b'Gasto de Capital'), (2, b'Aplicacion financiera')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tipoingreso',
            name='clasificacion',
            field=models.IntegerField(choices=[(
                0, b'Ingreso Corriente'), (1, b'Ingreso Capital'), (2, b'Financiamiento Deficit')], default=0, null=True),
        ),
    ]
