# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-25 16:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200423_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenIngresosCorrientes',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre')),
                ('shortname', models.CharField(blank=True, max_length=25, null=True)),
                ('orden', models.IntegerField()),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'verbose_name': 'Origen de Ingreso Corriente',
                'verbose_name_plural': 'Origen de Ingresos Corrientes',
            },
        ),
    ]
