# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_origeningresoscorrientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtipoingreso',
            name='origen_ic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.OrigenIngresosCorrientes', verbose_name=b'Origen ingreso corriente'),
        ),
    ]
