# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200425_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubtipogasto',
            name='origen_gc',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.
                                    models.deletion.CASCADE,
                                    to='core.OrigenGastosCorrientes',
                                    verbose_name=b'Origen Gasto de Corriente'),
        ),
    ]
