# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 04:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('vertical', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('enlace', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'banner')),
                ('color', models.CharField(max_length=6)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name=b'fecha')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=b'documentos')),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'documento')),
            ],
            options={
                'ordering': ['titulo'],
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'titulo')),
            ],
            options={
                'verbose_name': 'Tipo',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo', to='website.TipoDoc'),
        ),
    ]
