# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 02:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20151203_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['titulo'], 'verbose_name': 'Documentos',
                     'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='tipodoc',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'titulo'),
        ),
    ]
