# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-23 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.IntegerField(verbose_name='Desde')),
                ('hasta', models.IntegerField(verbose_name='Hasta')),
            ],
            options={
                'ordering': ['desde'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoMunic',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.CharField(max_length=30, null=True)),
                ('municipio', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Periodo')),
            ],
            options={
                'ordering': ['periodo'],
            },
        ),
    ]
