# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 02:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0019_auto_20151203_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comarca',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'nombre', verbose_name=b'municipio'),
        ),
    ]
